import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/providers/store-provider";
import { Toaster } from "react-hot-toast";
import HomepageLayout from "../components/layout/homepage-layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HomepageLayout>
          <StoreProvider>{children}</StoreProvider>
          <Toaster />
        </HomepageLayout>
      </body>
    </html>
  );
}
